version: '3.5'

volumes:
  gems-app:

services:
  web:
    tty: true
    stdin_open: true
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/usr/src/app
      - gems-app:/usr/local/bundle
    ports:
      - "3000:3000"
      - "3035:3035"
    links:
      - db-my-app
    environment:
      TZ:           America/Sao_Paulo
      DATABASE_URL: postgres://postgres@db-my-app

  db-my-app:
    image: postgres
    ports:
      - "5432:5432"

# networks:
#   default:
#     external:
#       name: my-app
