version: '3.5'

volumes:
  gems-app:

services:
  web:
    tty: true
    stdin_open: true
    build: .
    command: foreman start -f Procfile.dev
    volumes:
      - ./:/usr/src/app
      - gems-app:/usr/local/bundle
    ports:
      - "3000:3000"
      - "3035:3035"
    links:
      - db-my-app
    environment:
      TZ:           America/Sao_Paulo
      DATABASE_URL: postgres://postgres@db-my-app

  db-my-app:
    image: postgres
    ports:
      - "5432:5432"

# networks:
#   default:
#     external:
#       name: my-app
