version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - BUNDLE_APP_CONFIG=/app/.bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpacker
  db:
    image: postgres
  webpacker:
    build: .
    command: bundle exec webpack-dev-server
    volumes:
      - .:/app
    ports:
      - "8080:8080"
volumes:
  bundle_path:
